PucsMVC/Controllers/ApoliceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;

using PucsMVC.Data;
using PucsMVC.Models.EF;

namespace PucsMVC.Controllers
{
    public class ApoliceController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ApoliceController(ApplicationDbContext context)
        {
            _context = context;
        }
        
        // GET: Apolice
        // A simple View is returned
        // The Grid will asyc call the Apolice_Read action on page load
        public IActionResult Index() => View();
        public async Task<IActionResult> Apolices_Read([DataSourceRequest]DataSourceRequest request)
        {
            var applicationDbContext = _context.Apolices.Include(a => a.Cliente).Include(a => a.Modelo);
            return Json(await applicationDbContext.ToDataSourceResultAsync(request));
        }

        // GET: Apolice/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var apolice = await _context.Apolices
                .Include(a => a.Cliente)
                .Include(a => a.Modelo)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (apolice == null)
            {
                return NotFound();
            }

            return View(apolice);
        }

        // GET: Apolice/Create
        public IActionResult Create()
        {
            ViewData["ClienteId"] = new SelectList(_context.Clientes, "Id", "RazaoSocial");
            ViewData["ModeloId"] = new SelectList(_context.Modelos, "Id", "NomeModelo");
            return View();
        }

        // POST: Apolice/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ClasseBonus,IdentificacaoApolice,DataInicioVigencia,DataFimVigencia,ClienteId,ModeloId,Id")] Apolice apolice)
        {
            if (ModelState.IsValid)
            {
                _context.Add(apolice);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ClienteId"] = new SelectList(_context.Clientes, "Id", "Id", apolice.ClienteId);
            ViewData["ModeloId"] = new SelectList(_context.Modelos, "Id", "Id", apolice.ModeloId);
            return View(apolice);
        }

        // GET: Apolice/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var apolice = await _context.Apolices.FindAsync(id);
            if (apolice == null)
            {
                return NotFound();
            }
            ViewData["ClienteId"] = new SelectList(_context.Clientes, "Id", "Id", apolice.ClienteId);
            ViewData["ModeloId"] = new SelectList(_context.Modelos, "Id", "Id", apolice.ModeloId);
            return View(apolice);
        }

        // POST: Apolice/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ClasseBonus,IdentificacaoApolice,DataInicioVigencia,DataFimVigencia,ClienteId,ModeloId,Id")] Apolice apolice)
        {
            if (id != apolice.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(apolice);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ApoliceExists(apolice.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ClienteId"] = new SelectList(_context.Clientes, "Id", "Id", apolice.ClienteId);
            ViewData["ModeloId"] = new SelectList(_context.Modelos, "Id", "Id", apolice.ModeloId);
            return View(apolice);
        }

        // GET: Apolice/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var apolice = await _context.Apolices
                .Include(a => a.Cliente)
                .Include(a => a.Modelo)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (apolice == null)
            {
                return NotFound();
            }

            return View(apolice);
        }

        // POST: Apolice/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var apolice = await _context.Apolices.FindAsync(id);
            _context.Apolices.Remove(apolice);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ApoliceExists(int id)
        {
            return _context.Apolices.Any(e => e.Id == id);
        }
    }
}

PucsMVC/Controllers/MarcasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;

using PucsMVC.Data;
using PucsMVC.Models.EF;
using PucsMVC.Interfaces.Repositories;
using PucsMVC.Interfaces.Services;

namespace PucsMVC.Controllers
{
    public class MarcasController : Controller
    {

        private readonly IServiceBase<Marca> _service;

        public MarcasController(IServiceBase<Marca> service)
        {
            _service = service;
        }

        // GET: Marcas
        // A simple View is returned
        // The Grid will asyc call the Marcas_Read action on page load
        public IActionResult Index() => View();
        public async Task<IActionResult> Marcas_Read([DataSourceRequest] DataSourceRequest request)
        {
            return Json(await _service.GetAll().ToDataSourceResultAsync(request));
        }

        // GET: Marcas/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var marca = _service.Get(c => c.Id == id);
            if (marca == null)
            {
                return NotFound();
            }

            return View(marca);
        }

        // GET: Marcas/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Marcas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("NomeMarca,Id")] Marca marca)
        {
            if (ModelState.IsValid)
            {
                _service.Add(marca);

                return RedirectToAction(nameof(Index));
            }
            return View(marca);
        }

        // GET: Marcas/Edit/5
        public IActionResult Edit(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var marca = _service.GetById(id);
            if (marca == null)
            {
                return NotFound();
            }
            return View(marca);
        }

        // POST: Marcas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("NomeMarca,Id")] Marca marca)
        {
            if (id != marca.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _service.Update(marca);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MarcaExists(marca.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(marca);
        }

        // GET: Marcas/Delete/5
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var marca = _service.Get(c => c.Id == id);
            if (marca == null)
            {
                return NotFound();
            }

            return View(marca);
        }

        // POST: Marcas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            var marca = _service.Get(c => c.Id == id);
            _service.Remove(marca);
            return RedirectToAction(nameof(Index));
        }

        private bool MarcaExists(int id)
        {
            return _service.Any(c => c.Id == id);
        }
    }
}

PucsMVC/Controllers/ModelosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;

using PucsMVC.Data;
using PucsMVC.Models.EF;

namespace PucsMVC.Controllers
{
    public class ModelosController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ModelosController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Modelos
        // A simple View is returned
        // The Grid will asyc call the Modelos_Read action on page load
        public IActionResult Index() => View();
        public async Task<IActionResult> Modelos_Read([DataSourceRequest] DataSourceRequest request)
        {
            var applicationDbContext = _context.Modelos.Include(m => m.Marca).ToList();
            return Json(await applicationDbContext.ToDataSourceResultAsync(request));
        }

        // GET: Modelos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var modelo = await _context.Modelos
                .Include(m => m.Marca)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (modelo == null)
            {
                return NotFound();
            }

            return View(modelo);
        }

        // GET: Modelos/Create
        public IActionResult Create()
        {
            ViewData["MarcaId"] = new SelectList(_context.Marcas, "Id", "NomeMarca");
            return View();
        }

        // POST: Modelos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("NomeModelo,MarcaId,Id")] Modelo modelo)
        {
            if (ModelState.IsValid)
            {
                _context.Add(modelo);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["MarcaId"] = new SelectList(_context.Marcas, "Id", "Id", modelo.MarcaId);
            return View(modelo);
        }

        // GET: Modelos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var modelo = await _context.Modelos.FindAsync(id);
            if (modelo == null)
            {
                return NotFound();
            }
            ViewData["MarcaId"] = new SelectList(_context.Marcas, "Id", "Id", modelo.MarcaId);
            return View(modelo);
        }

        // POST: Modelos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("NomeModelo,MarcaId,Id")] Modelo modelo)
        {
            if (id != modelo.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(modelo);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ModeloExists(modelo.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["MarcaId"] = new SelectList(_context.Marcas, "Id", "Id", modelo.MarcaId);
            return View(modelo);
        }

        // GET: Modelos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var modelo = await _context.Modelos
                .Include(m => m.Marca)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (modelo == null)
            {
                return NotFound();
            }

            return View(modelo);
        }

        // POST: Modelos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var modelo = await _context.Modelos.FindAsync(id);
            _context.Modelos.Remove(modelo);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ModeloExists(int id)
        {
            return _context.Modelos.Any(e => e.Id == id);
        }
    }
}

PucsMVC/Views/Shared/_Layout.cshtml
@using Kendo.Mvc.UI;
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PucsMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PucsMVC.styles.css" asp-append-version="true" />
    <link href="https://cdn.kendostatic.com/2022.1.412/styles/kendo.classic-silver.min.css" rel="stylesheet" type="text/css" />
    <script src="https://cdn.kendostatic.com/2022.1.412/js/jquery.min.js"></script>
    <script src="https://cdn.kendostatic.com/2022.1.412/js/jszip.min.js"></script>
    <script src="https://cdn.kendostatic.com/2022.1.412/js/kendo.all.min.js"></script>
    <script src="https://cdn.kendostatic.com/2022.1.412/js/kendo.aspnetmvc.min.js"></script>
</head>
<body class="k-content">
    <header>
        @* <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PucsMVC</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
        <ul class="navbar-nav flex-grow-1">
        <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
        </li>
        <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </li>
        </ul>
        @if (SignInManager.IsSignedIn(User))
        {
        <ul class="navbar-nav flex-grow-1">
        <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Clientes" asp-action="Index">Clientes</a>
        </li>
        <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Marcas" asp-action="Index">Marcas</a>
        </li>
        <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Modelos" asp-action="Index">Modelos</a>
        </li>
        <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Apolices" asp-action="Index">Apolices</a>
        </li>
        </ul>
        }
        <partial name="_LoginPartial" />
        </div>
        </div>
        </nav>*@

        <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
            <div class="container">
                <a asp-controller="Home" asp-action="Index" class="navbar-brand mb-0 h1">Pucs</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-content">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbar-content" role="tablist">
                    @if (SignInManager.IsSignedIn(User))
                    {
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Clientes" asp-action="Index">Clientes</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Marcas" asp-action="Index">Marcas</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Modelos" asp-action="Index">Modelos</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Apolice" asp-action="Index">Apolices</a>
                            </li>
                        </ul>
                    }
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>




    </header>





    <main role="main" class="pb-3">
        <div class="container-fluid">
            @RenderBody()
        </div>

    </main>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - PucsMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>